services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loyalty-app
    restart: unless-stopped
    working_dir: /var/www

    volumes:
      - ./:/var/www
      - vendor:/var/www/vendor
      - storage:/var/www/storage
      - bootstrap-cache:/var/www/bootstrap/cache

    depends_on:
      redis:
        condition: service_healthy

    networks:
      - loyalty-network

  nginx:
    image: nginx:alpine
    container_name: loyalty-nginx
    restart: unless-stopped
    ports:
      - "8088:80"

    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro

    depends_on:
      - app

    networks:
      - loyalty-network

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loyalty-queue-worker
    restart: unless-stopped
    working_dir: /var/www

    volumes:
      - ./:/var/www
      - vendor:/var/www/vendor
      - storage:/var/www/storage
      - bootstrap-cache:/var/www/bootstrap/cache

    depends_on:
      redis:
        condition: service_healthy

    command: php artisan queue:work --tries=3

    networks:
      - loyalty-network

  redis:
    image: redis:7-alpine
    container_name: loyalty-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    networks:
      - loyalty-network

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  loyalty-network:
    driver: bridge

volumes:
  vendor:
    driver: local

  storage:
    driver: local

  bootstrap-cache:
    driver: local

  redis-data:
    driver: local